apiVersion: v1
kind: Service
metadata:
  name: default-subdomain
spec:
  selector:
    app: busybox
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: busybox
  labels:
    name: busybox
    app: busybox
spec:
  serviceName: busybox
  replicas: 3
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - image: busybox
        command:
          - sleep
          - "3600"
        name: busybox